### ISSUE TITLE
Workflow failure and PR never gets created.

### ISSUE THREAD

**Issue by fabiocaccamo** [browniebroke/pre-commit-autoupdate-action#2]
Hi @browniebroke,
thank you for this nice action!

I'm using `pre-commit-autoupdate-action` and I'm finding myself at a dead end where the workflow fails when running `pre-commit run --all-files` because some files are reformatted by `black`, then the pull-request is never created:

<img width="489" alt="Screenshot 2024-03-06 at 14 29 42" src="https://github.com/browniebroke/pre-commit-autoupdate-action/assets/1035294/cb7f7466-8d7f-4fd9-848f-af690cf44991">

The goal of this action should bounded to update the hooks and running `pre-commit` on all files should be optional, do you agree?

**Comment by browniebroke** [comment]
Yes, probably. I chose to run `pre-commit run --all-files` in the workflow because by default, PR opened aren't triggering GitHub actions, and I wanted to avoid merging PRs with failure that I couldn't see. 

However, as you pointed out, not having a PR at all is not very helpful...

**Comment by browniebroke** [comment]
For what it's worth, I'm not using this action anymore, but instead I switched to reusable workflow, which let me combine multiple actions: https://github.com/browniebroke/github-actions?tab=readme-ov-file#pre-commit-auto-update

However, it suffers from the same problem: https://github.com/browniebroke/github-actions/blob/65c4d9afdb3c08a68ad30b0db324162695dc809b/.github/workflows/pre-commit-autoupdate.yml#L45-L46

**Comment by fabiocaccamo** [comment]
> because by default, PR opened aren't triggering GitHub actions, and I wanted to avoid merging PRs with failure that I couldn't see.

Thank you for the explanation, sounds reasonable.

I achieved the desired result by running commands without using the action:

```yaml
# ...

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      
      # ...

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Update pre-commit hooks
        run: |
          pre-commit autoupdate

      - name: Create pull-request
        uses: peter-evans/create-pull-request@v6
        
        # ...
```
